### ISSUE TITLE
Obter modelos de casos de uso

### ISSUE THREAD

**Issue by trspecht** [trspecht/WaspEnterprises#1]

**Comment by RafaGH** [comment]
Soh pra tu comparar neh

**Comment by trspecht** [comment]
Óbvio. Eu sempre comparo. Mas é só pra ajudar os colegas a melhorarem os seus próprios códigos.

**Comment by matuella** [comment]
Issue #1 :
Eliminar Rafael do Trabalho.

2015-09-25 10:15 GMT-03:00 Tainara Specht <notifications@github.com>:

**Comment by dvpeixoto** [comment]
Coffe rules!
